"use client";

import { useState } from "react";
import BinIcon from "../Icons/BinIcon";
import PenIcon from "../Icons/PenIcon";
import styles from "./AITask.module.css";
import { GeneratedTask } from "@/models/tasks.model";
import classNames from "classnames";

interface AITaskProps {
  task: GeneratedTask;
  deleteTask: () => void;
  updateTask: (task: GeneratedTask) => void;
}

/**
 * AITask component displays a single task generated by AI.
 * It allows users to view, edit, and delete the task.
 * 
 * @param {AITaskProps} props - The properties for the AITask component.
 * @returns {JSX.Element} The rendered AITask component.
 */
export default function AITask({ task, deleteTask, updateTask }: AITaskProps) {
  // State to track if the task is currently in edit mode
  const [isModifying, setIsModifying] = useState(false);
  // Local state to hold temporary changes before saving to the parent state
  const [localTask, setLocalTask] = useState(task);

  /**
   * Persists the local changes by calling the updateTask callback.
   */
  const handleSave = () => {
    updateTask(localTask);
  };

  /**
   * Toggles between view and edit modes. 
   * If exiting edit mode, it triggers the save operation.
   */
  const toggleModify = () => {
    if (isModifying) {
      handleSave();
    }
    setIsModifying(!isModifying);
  };

  return (
    <div className={styles.container}>
      {!isModifying && (
        <div className={styles.taskDetail}>
          <h3 className={styles.title}>{task.title}</h3>
          <p className={styles.description}>{task.description}</p>
        </div>
      )}

      {isModifying && (
        <div className={styles.taskDetail}>
          <input
            type="text"
            className={styles.input}
            value={localTask.title}
            onChange={(e) =>
              setLocalTask({ ...localTask, title: e.target.value })
            }
          />
          <input
            type="text"
            className={styles.input}
            value={localTask.description}
            onChange={(e) =>
              /* Updates only the description field while preserving other task properties */
              setLocalTask({ ...task, description: e.target.value })
            }
          />
        </div>
      )}

      <div className={styles.tools}>
        <span className={styles.tool} onClick={() => deleteTask()}>
          <BinIcon /> Supprimer
        </span>
        <span>|</span>
        <span
          className={classNames([styles.tool, styles.modify])}
          onClick={() => toggleModify()}
        >
          <PenIcon /> {isModifying ? "Fin modification" : "Modifier"}
        </span>
      </div>
    </div>
  );
}
