/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * API Gestionnaire de Projets
 * API REST pour la gestion de projets, tâches et commentaires avec authentification JWT
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Error,
  GetUsersSearch200,
  GetUsersSearchParams
} from '../../models';





/**
 * @summary Rechercher des utilisateurs pour l'autocomplete
 */
export type getUsersSearchResponse200 = {
  data: GetUsersSearch200
  status: 200
}

export type getUsersSearchResponse400 = {
  data: Error
  status: 400
}

export type getUsersSearchResponse401 = {
  data: Error
  status: 401
}

export type getUsersSearchResponseSuccess = (getUsersSearchResponse200) & {
  headers: Headers;
};
export type getUsersSearchResponseError = (getUsersSearchResponse400 | getUsersSearchResponse401) & {
  headers: Headers;
};

export type getUsersSearchResponse = (getUsersSearchResponseSuccess | getUsersSearchResponseError)

export const getGetUsersSearchUrl = (params: GetUsersSearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/users/search?${stringifiedParams}` : `/users/search`
}

export const getUsersSearch = async (params: GetUsersSearchParams, options?: RequestInit): Promise<getUsersSearchResponse> => {
  
  const res = await fetch(getGetUsersSearchUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getUsersSearchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUsersSearchResponse
}
  




export const getGetUsersSearchQueryKey = (params?: GetUsersSearchParams,) => {
    return [
    `/users/search`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetUsersSearchQueryOptions = <TData = Awaited<ReturnType<typeof getUsersSearch>>, TError = Error>(params: GetUsersSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersSearch>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUsersSearchQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersSearch>>> = ({ signal }) => getUsersSearch(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUsersSearch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUsersSearchQueryResult = NonNullable<Awaited<ReturnType<typeof getUsersSearch>>>
export type GetUsersSearchQueryError = Error


export function useGetUsersSearch<TData = Awaited<ReturnType<typeof getUsersSearch>>, TError = Error>(
 params: GetUsersSearchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersSearch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersSearch>>,
          TError,
          Awaited<ReturnType<typeof getUsersSearch>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersSearch<TData = Awaited<ReturnType<typeof getUsersSearch>>, TError = Error>(
 params: GetUsersSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersSearch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUsersSearch>>,
          TError,
          Awaited<ReturnType<typeof getUsersSearch>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUsersSearch<TData = Awaited<ReturnType<typeof getUsersSearch>>, TError = Error>(
 params: GetUsersSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersSearch>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Rechercher des utilisateurs pour l'autocomplete
 */

export function useGetUsersSearch<TData = Awaited<ReturnType<typeof getUsersSearch>>, TError = Error>(
 params: GetUsersSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUsersSearch>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUsersSearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




