/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * API Gestionnaire de Projets
 * API REST pour la gestion de projets, tâches et commentaires avec authentification JWT
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Error,
  GetDashboardAssignedTasks200,
  GetDashboardProjectsWithTasks200
} from '../../models';





/**
 * @summary Récupérer les tâches assignées à l'utilisateur connecté
 */
export type getDashboardAssignedTasksResponse200 = {
  data: GetDashboardAssignedTasks200
  status: 200
}

export type getDashboardAssignedTasksResponse401 = {
  data: Error
  status: 401
}

export type getDashboardAssignedTasksResponseSuccess = (getDashboardAssignedTasksResponse200) & {
  headers: Headers;
};
export type getDashboardAssignedTasksResponseError = (getDashboardAssignedTasksResponse401) & {
  headers: Headers;
};

export type getDashboardAssignedTasksResponse = (getDashboardAssignedTasksResponseSuccess | getDashboardAssignedTasksResponseError)

export const getGetDashboardAssignedTasksUrl = () => {


  

  return `/dashboard/assigned-tasks`
}

export const getDashboardAssignedTasks = async ( options?: RequestInit): Promise<getDashboardAssignedTasksResponse> => {
  
  const res = await fetch(getGetDashboardAssignedTasksUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getDashboardAssignedTasksResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getDashboardAssignedTasksResponse
}
  




export const getGetDashboardAssignedTasksQueryKey = () => {
    return [
    `/dashboard/assigned-tasks`
    ] as const;
    }

    
export const getGetDashboardAssignedTasksQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardAssignedTasks>>, TError = Error>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardAssignedTasks>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardAssignedTasksQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardAssignedTasks>>> = ({ signal }) => getDashboardAssignedTasks({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboardAssignedTasks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDashboardAssignedTasksQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardAssignedTasks>>>
export type GetDashboardAssignedTasksQueryError = Error


export function useGetDashboardAssignedTasks<TData = Awaited<ReturnType<typeof getDashboardAssignedTasks>>, TError = Error>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardAssignedTasks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardAssignedTasks>>,
          TError,
          Awaited<ReturnType<typeof getDashboardAssignedTasks>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardAssignedTasks<TData = Awaited<ReturnType<typeof getDashboardAssignedTasks>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardAssignedTasks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardAssignedTasks>>,
          TError,
          Awaited<ReturnType<typeof getDashboardAssignedTasks>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardAssignedTasks<TData = Awaited<ReturnType<typeof getDashboardAssignedTasks>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardAssignedTasks>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Récupérer les tâches assignées à l'utilisateur connecté
 */

export function useGetDashboardAssignedTasks<TData = Awaited<ReturnType<typeof getDashboardAssignedTasks>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardAssignedTasks>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDashboardAssignedTasksQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Récupérer les projets dans lesquels l'utilisateur a des tâches assignées
 */
export type getDashboardProjectsWithTasksResponse200 = {
  data: GetDashboardProjectsWithTasks200
  status: 200
}

export type getDashboardProjectsWithTasksResponse401 = {
  data: Error
  status: 401
}

export type getDashboardProjectsWithTasksResponseSuccess = (getDashboardProjectsWithTasksResponse200) & {
  headers: Headers;
};
export type getDashboardProjectsWithTasksResponseError = (getDashboardProjectsWithTasksResponse401) & {
  headers: Headers;
};

export type getDashboardProjectsWithTasksResponse = (getDashboardProjectsWithTasksResponseSuccess | getDashboardProjectsWithTasksResponseError)

export const getGetDashboardProjectsWithTasksUrl = () => {


  

  return `/dashboard/projects-with-tasks`
}

export const getDashboardProjectsWithTasks = async ( options?: RequestInit): Promise<getDashboardProjectsWithTasksResponse> => {
  
  const res = await fetch(getGetDashboardProjectsWithTasksUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getDashboardProjectsWithTasksResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getDashboardProjectsWithTasksResponse
}
  




export const getGetDashboardProjectsWithTasksQueryKey = () => {
    return [
    `/dashboard/projects-with-tasks`
    ] as const;
    }

    
export const getGetDashboardProjectsWithTasksQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardProjectsWithTasks>>, TError = Error>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardProjectsWithTasks>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardProjectsWithTasksQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardProjectsWithTasks>>> = ({ signal }) => getDashboardProjectsWithTasks({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboardProjectsWithTasks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDashboardProjectsWithTasksQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardProjectsWithTasks>>>
export type GetDashboardProjectsWithTasksQueryError = Error


export function useGetDashboardProjectsWithTasks<TData = Awaited<ReturnType<typeof getDashboardProjectsWithTasks>>, TError = Error>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardProjectsWithTasks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardProjectsWithTasks>>,
          TError,
          Awaited<ReturnType<typeof getDashboardProjectsWithTasks>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardProjectsWithTasks<TData = Awaited<ReturnType<typeof getDashboardProjectsWithTasks>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardProjectsWithTasks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardProjectsWithTasks>>,
          TError,
          Awaited<ReturnType<typeof getDashboardProjectsWithTasks>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardProjectsWithTasks<TData = Awaited<ReturnType<typeof getDashboardProjectsWithTasks>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardProjectsWithTasks>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Récupérer les projets dans lesquels l'utilisateur a des tâches assignées
 */

export function useGetDashboardProjectsWithTasks<TData = Awaited<ReturnType<typeof getDashboardProjectsWithTasks>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardProjectsWithTasks>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDashboardProjectsWithTasksQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




