/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * API Gestionnaire de Projets
 * API REST pour la gestion de projets, tâches et commentaires avec authentification JWT
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Error,
  GetProjects200,
  GetProjectsIdTasks200,
  PostProjects201,
  PostProjectsBody
} from '../../models';





/**
 * @summary Créer un nouveau projet
 */
export type postProjectsResponse201 = {
  data: PostProjects201
  status: 201
}

export type postProjectsResponse400 = {
  data: Error
  status: 400
}

export type postProjectsResponse401 = {
  data: Error
  status: 401
}

export type postProjectsResponseSuccess = (postProjectsResponse201) & {
  headers: Headers;
};
export type postProjectsResponseError = (postProjectsResponse400 | postProjectsResponse401) & {
  headers: Headers;
};

export type postProjectsResponse = (postProjectsResponseSuccess | postProjectsResponseError)

export const getPostProjectsUrl = () => {


  

  return `/projects`
}

export const postProjects = async (postProjectsBody: PostProjectsBody, options?: RequestInit): Promise<postProjectsResponse> => {
  
  const res = await fetch(getPostProjectsUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postProjectsBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postProjectsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postProjectsResponse
}
  



export const getPostProjectsMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postProjects>>, TError,{data: PostProjectsBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postProjects>>, TError,{data: PostProjectsBody}, TContext> => {

const mutationKey = ['postProjects'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postProjects>>, {data: PostProjectsBody}> = (props) => {
          const {data} = props ?? {};

          return  postProjects(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostProjectsMutationResult = NonNullable<Awaited<ReturnType<typeof postProjects>>>
    export type PostProjectsMutationBody = PostProjectsBody
    export type PostProjectsMutationError = Error

    /**
 * @summary Créer un nouveau projet
 */
export const usePostProjects = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postProjects>>, TError,{data: PostProjectsBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postProjects>>,
        TError,
        {data: PostProjectsBody},
        TContext
      > => {
      return useMutation(getPostProjectsMutationOptions(options), queryClient);
    }
    /**
 * @summary Récupérer tous les projets de l'utilisateur connecté
 */
export type getProjectsResponse200 = {
  data: GetProjects200
  status: 200
}

export type getProjectsResponse401 = {
  data: Error
  status: 401
}

export type getProjectsResponseSuccess = (getProjectsResponse200) & {
  headers: Headers;
};
export type getProjectsResponseError = (getProjectsResponse401) & {
  headers: Headers;
};

export type getProjectsResponse = (getProjectsResponseSuccess | getProjectsResponseError)

export const getGetProjectsUrl = () => {


  

  return `/projects`
}

export const getProjects = async ( options?: RequestInit): Promise<getProjectsResponse> => {
  
  const res = await fetch(getGetProjectsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getProjectsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getProjectsResponse
}
  




export const getGetProjectsQueryKey = () => {
    return [
    `/projects`
    ] as const;
    }

    
export const getGetProjectsQueryOptions = <TData = Awaited<ReturnType<typeof getProjects>>, TError = Error>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProjectsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProjects>>> = ({ signal }) => getProjects({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProjectsQueryResult = NonNullable<Awaited<ReturnType<typeof getProjects>>>
export type GetProjectsQueryError = Error


export function useGetProjects<TData = Awaited<ReturnType<typeof getProjects>>, TError = Error>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjects>>,
          TError,
          Awaited<ReturnType<typeof getProjects>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjects<TData = Awaited<ReturnType<typeof getProjects>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjects>>,
          TError,
          Awaited<ReturnType<typeof getProjects>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjects<TData = Awaited<ReturnType<typeof getProjects>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Récupérer tous les projets de l'utilisateur connecté
 */

export function useGetProjects<TData = Awaited<ReturnType<typeof getProjects>>, TError = Error>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProjectsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Retourne la liste complète des tâches associées à un projet spécifique, incluant les détails du créateur, les assignations et les commentaires
 * @summary Récupérer toutes les tâches d'un projet
 */
export type getProjectsIdTasksResponse200 = {
  data: GetProjectsIdTasks200
  status: 200
}

export type getProjectsIdTasksResponse401 = {
  data: Error
  status: 401
}

export type getProjectsIdTasksResponse403 = {
  data: Error
  status: 403
}

export type getProjectsIdTasksResponse500 = {
  data: Error
  status: 500
}

export type getProjectsIdTasksResponseSuccess = (getProjectsIdTasksResponse200) & {
  headers: Headers;
};
export type getProjectsIdTasksResponseError = (getProjectsIdTasksResponse401 | getProjectsIdTasksResponse403 | getProjectsIdTasksResponse500) & {
  headers: Headers;
};

export type getProjectsIdTasksResponse = (getProjectsIdTasksResponseSuccess | getProjectsIdTasksResponseError)

export const getGetProjectsIdTasksUrl = (id: string,) => {


  

  return `/projects/${id}/tasks`
}

export const getProjectsIdTasks = async (id: string, options?: RequestInit): Promise<getProjectsIdTasksResponse> => {
  
  const res = await fetch(getGetProjectsIdTasksUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getProjectsIdTasksResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getProjectsIdTasksResponse
}
  




export const getGetProjectsIdTasksQueryKey = (id: string,) => {
    return [
    `/projects/${id}/tasks`
    ] as const;
    }

    
export const getGetProjectsIdTasksQueryOptions = <TData = Awaited<ReturnType<typeof getProjectsIdTasks>>, TError = Error>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectsIdTasks>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProjectsIdTasksQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProjectsIdTasks>>> = ({ signal }) => getProjectsIdTasks(id, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProjectsIdTasks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProjectsIdTasksQueryResult = NonNullable<Awaited<ReturnType<typeof getProjectsIdTasks>>>
export type GetProjectsIdTasksQueryError = Error


export function useGetProjectsIdTasks<TData = Awaited<ReturnType<typeof getProjectsIdTasks>>, TError = Error>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectsIdTasks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectsIdTasks>>,
          TError,
          Awaited<ReturnType<typeof getProjectsIdTasks>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjectsIdTasks<TData = Awaited<ReturnType<typeof getProjectsIdTasks>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectsIdTasks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjectsIdTasks>>,
          TError,
          Awaited<ReturnType<typeof getProjectsIdTasks>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProjectsIdTasks<TData = Awaited<ReturnType<typeof getProjectsIdTasks>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectsIdTasks>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Récupérer toutes les tâches d'un projet
 */

export function useGetProjectsIdTasks<TData = Awaited<ReturnType<typeof getProjectsIdTasks>>, TError = Error>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProjectsIdTasks>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProjectsIdTasksQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




