/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * API Gestionnaire de Projets
 * API REST pour la gestion de projets, tâches et commentaires avec authentification JWT
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';

export interface Comment {
  /** ID unique du commentaire */
  id: string;
  /** Contenu du commentaire */
  content: string;
  /** ID de la tâche associée */
  taskId: string;
  /** ID de l'auteur du commentaire */
  authorId: string;
  author?: User;
  createdAt?: string;
  updatedAt?: string;
}
