/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * API Gestionnaire de Projets
 * API REST pour la gestion de projets, tâches et commentaires avec authentification JWT
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorDetailsItem } from './errorDetailsItem';

export interface Error {
  success?: boolean;
  /** Message d'erreur */
  message?: string;
  /** Code d'erreur */
  error?: string;
  details?: ErrorDetailsItem[];
}
