/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * API Gestionnaire de Projets
 * API REST pour la gestion de projets, tâches et commentaires avec authentification JWT
 * OpenAPI spec version: 1.0.0
 */
import type { GetDashboardProjectsWithTasks200DataProjectsItem } from './getDashboardProjectsWithTasks200DataProjectsItem';

export type GetDashboardProjectsWithTasks200Data = {
  projects?: GetDashboardProjectsWithTasks200DataProjectsItem[];
};
