/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * API Gestionnaire de Projets
 * API REST pour la gestion de projets, tâches et commentaires avec authentification JWT
 * OpenAPI spec version: 1.0.0
 */
import type { PostAuthLogin200Data } from './postAuthLogin200Data';
import type { Success } from './success';

export type PostAuthLogin200 = Success & {
  data?: PostAuthLogin200Data;
};
