/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * API Gestionnaire de Projets
 * API REST pour la gestion de projets, tâches et commentaires avec authentification JWT
 * OpenAPI spec version: 1.0.0
 */

export type PostAuthRegisterBody = {
  /** Email de l'utilisateur */
  email: string;
  /**
   * Mot de passe (minimum 6 caractères)
   * @minLength 6
   */
  password: string;
  /** Nom de l'utilisateur */
  name: string;
};
