/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * API Gestionnaire de Projets
 * API REST pour la gestion de projets, tâches et commentaires avec authentification JWT
 * OpenAPI spec version: 1.0.0
 */

export type PostAuthLoginBody = {
  /** Email de l'utilisateur */
  email: string;
  /** Mot de passe */
  password: string;
};
