/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * API Gestionnaire de Projets
 * API REST pour la gestion de projets, tâches et commentaires avec authentification JWT
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectMemberRole } from './projectMemberRole';
import type { User } from './user';

export interface ProjectMember {
  id?: string;
  /** Rôle de l'utilisateur dans le projet */
  role?: ProjectMemberRole;
  user?: User;
  joinedAt?: string;
}
