/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * API Gestionnaire de Projets
 * API REST pour la gestion de projets, tâches et commentaires avec authentification JWT
 * OpenAPI spec version: 1.0.0
 */
import type { ProjectMember } from './projectMember';
import type { User } from './user';

export interface Project {
  /** ID unique du projet */
  id: string;
  /** Nom du projet */
  name: string;
  /** Description du projet */
  description?: string;
  /** ID du propriétaire du projet */
  ownerId: string;
  owner?: User;
  members?: ProjectMember[];
  createdAt?: string;
  updatedAt?: string;
}
