/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * API Gestionnaire de Projets
 * API REST pour la gestion de projets, tâches et commentaires avec authentification JWT
 * OpenAPI spec version: 1.0.0
 */

/**
 * Rôle de l'utilisateur dans le projet
 */
export type ProjectMemberRole = typeof ProjectMemberRole[keyof typeof ProjectMemberRole];


export const ProjectMemberRole = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  CONTRIBUTOR: 'CONTRIBUTOR',
} as const;
