/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * API Gestionnaire de Projets
 * API REST pour la gestion de projets, tâches et commentaires avec authentification JWT
 * OpenAPI spec version: 1.0.0
 */
import type { SuccessData } from './successData';

export interface Success {
  success?: boolean;
  /** Message de succès */
  message?: string;
  /** Données de la réponse */
  data?: SuccessData;
}
