/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * API Gestionnaire de Projets
 * API REST pour la gestion de projets, tâches et commentaires avec authentification JWT
 * OpenAPI spec version: 1.0.0
 */
import type { User } from './user';

export interface TaskAssignee {
  id?: string;
  userId?: string;
  taskId?: string;
  user?: User;
  assignedAt?: string;
}
