/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * API Gestionnaire de Projets
 * API REST pour la gestion de projets, tâches et commentaires avec authentification JWT
 * OpenAPI spec version: 1.0.0
 */
import type { Comment } from './comment';
import type { TaskAssignee } from './taskAssignee';
import type { TaskPriority } from './taskPriority';
import type { TaskStatus } from './taskStatus';

export interface Task {
  /** ID unique de la tâche */
  id: string;
  /** Titre de la tâche */
  title: string;
  /** Description de la tâche */
  description?: string;
  /** Statut de la tâche */
  status: TaskStatus;
  /** Priorité de la tâche */
  priority: TaskPriority;
  /** Date d'échéance de la tâche */
  dueDate?: string;
  /** ID du projet associé */
  projectId: string;
  /** ID du créateur de la tâche */
  creatorId: string;
  assignees?: TaskAssignee[];
  comments?: Comment[];
  createdAt?: string;
  updatedAt?: string;
}
