/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * API Gestionnaire de Projets
 * API REST pour la gestion de projets, tâches et commentaires avec authentification JWT
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  /** ID unique de l'utilisateur */
  id: string;
  /** Email de l'utilisateur */
  email: string;
  /** Nom de l'utilisateur */
  name?: string;
  /** Date de création du compte */
  createdAt?: string;
  /** Date de dernière modification */
  updatedAt?: string;
}
